spring:
  application.name: EurekaServer
  profiles: peer1

server:
  port: 8000

eureka:
  instance:
    hostname: peer1
    appname: eureka-cluster
  client:
    registerWithEureka: false
    fetchRegistery: false
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/

---

spring:
  application.name: EurekaServer
  profiles: peer2

server:
  port: 8001

eureka:
  instance:
    hostname: peer2
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/
